# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f2d7378a10de6e6d0ddf3ab9fedcd0f7"
name = "product-sync-center-app"
application_url = "https://product-sync-center.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://product-sync-center.onrender.com/api/auth",
  "https://product-sync-center.onrender.com/auth/callback",
  "https://product-sync-center.onrender.com/api/auth/callback"
]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
